# Site settings
title: Retno Wulandari Personal Site
name: Retno Wulandari Personal Site
url: "http://retnow22.github.io"
email: retno22.wulandari@gmail.com
description: Retno Wulandari Personal Site 
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: retnow22  # Twitter ID
github_username:  retnow22 # Github ID
facebook_username: Retno Wulandari  # Facebook ID
duoshuo_username: waylau # Duoshuo ID
rss_url: "/feed.xml"  # RSS 订阅 URL
logo_image: ""  # LOGO 图片地址
# Build settings
gems: [jekyll-paginate]
markdown: rdiscount
highlighter: pygments
permalink: /:title/
paginate: 8
paginate_path: page/:num
 
